apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://localhost:3000/api"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "Ua7/o+ILbS5Xvla/3PoQp9VM+/6OvZO9Os6S6MQ4/Rw="
  JWT_SECRET: "1c9c23ba52158253904eb9e66efa8db258147324123e1f87e906b0adfaad332f"
