apiVersion: v1
kind: Service
metadata:
  name: easyshop-service
  namespace: easyshop
spec:
  type: NodePort
  ports:
    - port: 80 #service port (other Kubernetes resources can communicate)
      targetPort: 3000  #application port
      nodePort: 30000 #outside access
  selector:
    app: easyshop
