apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
      - name: migration
        image: aakash969/e-commerce-app-migration:2f808ad3544184ef7bcf261690233bc64604c5bb
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
