apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migration-
  namespace: easyshop
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: db-migration

    spec:
      restartPolicy: Never

      containers:
        - name: db-migration
          image: aakash969/e-commerce-migration:be3039f8744c1a602b0116b5b802be2be01080ea
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: easyshop-config

            - secretRef:
                name: easyshop-secrets