apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migration-
  namespace: easyshop
  annotations:
    argocd.argoproj.io/hook: PreSync #database migration happens before the application deployment.
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation #ells Argo CD to remove an old migration hook before creating the next one.
spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: db-migration

    spec:
      restartPolicy: Never

      containers:
        - image: aakash969/e-commerce-migration:2417b740dd12229ca8975700dbd9b7941fec7edd
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: easyshop-config

            - secretRef:
                name: easyshop-secrets